### ISSUE TITLE
Reorganization of home directory to improve documentation

### ISSUE THREAD

**Issue by adam2392** [cronelab/ReconstructionVisualizer#9]
In order to robustify the visualizer, one would seek to add unit tests, and documentation on i) installation and setup, ii) usage, and iii) how to contribute in development.

First, we might think of cleaning up the home dir.
1. Related FreeSurfer dockerfiles/files are not needed anymore if we utilize the one in neuroseek's dockerhub
2. Rename `src/` -> `seek_viz`?
3. Remove all of `scripts/`. 

Related Note
-------------
We can add a seek-meshgenerator repository that houses the mesh generator. Will try to organize that asap.

**Comment by TheBrainChain** [comment]
+1 for (2) Those are only the source files for the visualizer. 
So 1 and 3 need to stay because this repo currently serves as the source files for the docker images. (Every commit will cause a new image to be built and pushed to dockerhub)
